- name : Configure Docker on EC2 Instances
  hosts : all
  become: true
  connection : ssh
  tasks : 
  - name: updating apt
    command : apt update -y

  - name : Install Docker
    command : apt install -y docker.io
    become : yes
    become_user : root

  - name : Start Docker Service
    command : systemctl start docker
    become : yes
    become_user : root

  - name: Deploy Docker Container
    command: docker run -itd -p 8086:8081 krishnaobbu/app.jar:latest 
